// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7LJjw8h3HCj89Wk5WcOBjJrp7_dZ_0c',
    appId: '1:703471362747:web:29e36bed60c52185d5ff9e',
    messagingSenderId: '703471362747',
    projectId: 'receiptin',
    authDomain: 'receiptin.firebaseapp.com',
    storageBucket: 'receiptin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTqIPG0nOmwiL8MJ6oiYFwvn3rRuIGRU',
    appId: '1:703471362747:android:7eaac32eb3e3615ad5ff9e',
    messagingSenderId: '703471362747',
    projectId: 'receiptin',
    storageBucket: 'receiptin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAsTMo5HCK2-m-KV_Tfom1fL9o7ldhqk',
    appId: '1:703471362747:ios:645d59fcd442ec94d5ff9e',
    messagingSenderId: '703471362747',
    projectId: 'receiptin',
    storageBucket: 'receiptin.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAsTMo5HCK2-m-KV_Tfom1fL9o7ldhqk',
    appId: '1:703471362747:ios:3786d81aafef0877d5ff9e',
    messagingSenderId: '703471362747',
    projectId: 'receiptin',
    storageBucket: 'receiptin.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
